export const HTTP = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHENTICATED: 401,
    NOT_FOUND: 404
}


export const TYPE_BOLETO = {

    PREFEITURA: 1,
    SANEAMENTO: 2,
    ENERGIA_ELETRICA: 3,
    TELECOMUNICACOES: 4,
    ORGAOS_GOVERNAMENTAIS: 5,
    CARNES_ASSEMELHADOS: 6,
    MULTAS_TRANSITO: 7,
    USO_BANCO:8,
    OUTROS:9,
    CARTAO_CREDITO:10

}
